version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspace:cached
    network_mode: service:regtest
    command: sleep infinity
  
  regtest:
    image: junderw/bitcoinjs-regtest-server
    restart: unless-stopped
